# Generated by Django 5.1.6 on 2025-02-23 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_lesson_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='new/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi'])]),
        ),
    ]
